### ISSUE TITLE
Build Error After Cloning

### ISSUE THREAD

**Issue by lukashambsch** [josephdyer/skeleventy#12]
After cloning the project, I'm getting the following build error.

```
(29:3) `@apply` cannot be used with .transition because .transition is included in multiple rulesets.
```

I think it's because the `transition` class name overlaps with the css property of the same name. When I change the class name and all of its references, it builds correctly.

**Comment by josephdyer** [comment]
Hey! I think it's because the latest version of Tailwind now supports transitions - probably something clashing. Thanks for this, I'll look into a fix :)

**Comment by theapplegates** [comment]
Must remember to check the open issues before going insane. It doesn't help that I know nothing about coding. I'll do as lukashambsch did as soon as I translate it and figure out how to do it :)

**Comment by josephdyer** [comment]
I've fixed it - as I suspected, just a clash of my own utility classes with Tailwind's newly added transition classes :)

@theapplegates, Skeleventy/Eleventy/Tailwind etc, is for more advanced developers - so you might struggle!
