### ISSUE TITLE
Deprecated core-js@2.6.11: core-js@<3 is no longer maintained

### ISSUE THREAD

**Issue by speeke** [josephdyer/skeleventy#13]
After downloading and installing the code I got the following warning:

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

Not sure if this needs addressing?

**Comment by josephdyer** [comment]
You don't need to worry too much as Skeleventy will still work fine - I believe it's related to Babel. 

I haven't tried updating the package but you could try `npm install --save core-js@^3` but maybe take a back up of what you're doing, as I haven't tried this out yet. 

I'll update the repo when I get some time. Thanks :)
