### ISSUE TITLE
How do I update the TailwindCSS version?

### ISSUE THREAD

**Issue by TedGoas** [josephdyer/skeleventy#15]
👋 This is more of a question than an issue.

How do I update TailwindCSS? I'm currently on `"tailwindcss": "^1.0.5"1` in my `package.json`. I see this repo is on `1.2.0`, which I'd love to be on (if nothing else to get my hands on CSS Grid classes). How can I update my project to use `1.2.0`?

This is my first time working with 11ty, Skeleventy, and TailwindCSS. Sorry for the noob question!

**Comment by theapplegates** [comment]
I am so new to this, but I think once you change the version number in the package.json you just re-run the install, such as npm install or yarn install again. Maybe someone else can correct me if I’m wrong.

**Comment by josephdyer** [comment]
Hey Ted,

You can try typing in terminal `npm install tailwindcss -D`

To see what packages are out of date type `npm outdated`

**Comment by TedGoas** [comment]
@josephdyer Brilliant, thanks so much!
