### ISSUE TITLE
Great project - but unable to deploy to Netlify

### ISSUE THREAD

**Issue by vermontdevil** [josephdyer/skeleventy#16]
I ran into this issue:

_Error: TemplateLayoutPathResolver directory does not exist for default: _includes_

Not sure what this means? I looked through 11ty website and it wasn't helpful at this point.

Thanks

**Comment by josephdyer** [comment]
Netlify only needs the `dist` folder. Not sure what you're doing to get that error?

**Comment by vermontdevil** [comment]
But gitignore has that folder listed and netlify is trying to run the src
files to install. Am I doing this wrong?

**Comment by vermontdevil** [comment]
Apparently I'm to drop in the dist folder on Netlify after doing npm run production. Seems to work. I was hoping for a connection between github repositiory and netlify with 11ty and this starter but doesn't seem to be the case? In any case this would do for now. 

Thanks again.

**Comment by josephdyer** [comment]
Well it sounds like you haven't configured Netlify correctly.

Once you point Netlify to your repo on GitHub, set up a build command in the settings of `npm run production`.

Then in your terminal run that command for your project to minify styles and script, then git commit/push to your repo, Netlify will see this and trigger a build.

**Comment by dundas** [comment]
Seeing this same issue. @vermontdevil - how were you able to resolve? 

Also tried deploying with the dist folder not working. 

<img width="882" alt="Screen Shot 2020-08-05 at 4 54 40 PM" src="https://user-images.githubusercontent.com/627426/89463183-89e95000-d73c-11ea-8f36-0411d324e46d.png">
