### ISSUE TITLE
Worth adding a netlify config file!

### ISSUE THREAD

**Issue by jonnyburch** [josephdyer/skeleventy#19]
Currently you need to manually change the build folder and command when adding to Netlify. Not hard to do but tripped me up for a few minutes when my build failed.

Easily fixed with a Netlify config file, which would set those automatically.

Something like: `netlify.toml`
```
[build]
  command = "npm run production"
  publish = "dist"
```

**Comment by josephdyer** [comment]
As it's more something someone can add in easily themselves, or just change in the dashboard, it's not really something I bothered doing. Thanks though will keep it in mind :)
