### ISSUE TITLE
Inconsistency in date formatting filter

### ISSUE THREAD

**Issue by Bassetts** [josephdyer/skeleventy#21]
The date formatting filter uses a mixture of UTC and local date functions. This could cause some weirdness in the date formatting. For example if the post date is `2020-12-31T23:00:00.000+00:00` but the timezone on the local system is Australian Eastern Standard Time (UTC+10) then the formatted date would be `1st January 2020` when it should be `1st January 2021`.

https://github.com/josephdyer/skeleventy/blob/de7741c4425b725c49602f0dab9de22cbca990f0/filters/dates.js#L32

**Comment by josephdyer** [comment]
Thanks - when I get chance I'll have a look into this :)
