### ISSUE TITLE
PurgeCSS configured with whitelist

### ISSUE THREAD

**Issue by cafca** [josephdyer/skeleventy#28]
I am maintaining a projects based off of this and I was wondering about the reason for this huge whitelist in the purgeCSS config. Why don't you just use purgeCSS without any config options at all?

https://github.com/josephdyer/skeleventy/blob/626e376b24d879ff345ad74381ef10c238082541/webpack.mix.js#L59-L81

**Comment by josephdyer** [comment]
Hey, yes some of that list can be trimmed. However I'm pretty sure when you run purge it removed some of the 'non-tailwind' classes from the HTML and it borks the styling.

These I think could be taken out:
```
     'body', 
     'html', 
     'a', 
     'h1', 
     'h2', 
     'h3', 
     'h4', 
     'p', 
     'blockquote',
```

**Comment by cafca** [comment]
I was able to remove purgeCss from `webpack.mix.js` entirely by adding `purge: ["./site/**/*.njk", "./site/**/*.md"],` to `tailwind.config.js`. That also uses purgeCss internally but you don't have to guess what you need to add to the whitelist.

**Comment by josephdyer** [comment]
Yes good idea :) I will look to do this in an update
