### ISSUE TITLE
ctrl+c doesn't seem to kill the Eleventy browsersync instance

### ISSUE THREAD

**Issue by wjthomas9** [josephdyer/skeleventy#3]
When using `npm run dev`, it fires up the Eleventy serve and gulp tasks fine, but when using ctrl+c, it only seems to stop gulp, not the eleventy server. 

Unless you close your terminal and re-open it, Eleventy will build twice next time, and incrementally from there if you continue to stop gulp and then re-run `npm run dev`. This only seems to be an issue when pairing it with gulp.

**Comment by josephdyer** [comment]
Hmm..this works fine for me? Ctrl + C kills localhost, saving files doesn't compile anything - completely as expected. Not quite sure what's going on for you :(

**Comment by NetLancer** [comment]
Dummy thought:
Does it stop server if no gulp used ?
Maybe - first try to figure out what the gulp config file says.
If it is as expected then why not use some alternative
like ForestMist/feri or whatever else

**Comment by wjthomas9** [comment]
I'll keep poking around. I had to convert to gulp 4, so maybe that's introducing some weirdness. We can close this and I'll re-open if I see it again and can provide steps to reproduce.
