### ISSUE TITLE
Netlify build error

### ISSUE THREAD

**Issue by chufucious** [josephdyer/skeleventy#31]
The local development version + Netlify production builds look different.

When I build on Netlify I get this error message:

```
The build completed successfully, but the following processes were still running:
5:29:57 PM: ​
5:29:57 PM:    - node /opt/build/repo/node_modules/.bin/mix --production
5:29:57 PM:    - /bin/sh -c npx webpack --config="node_modules/laravel-mix/setup/webpack.config.js"
5:29:57 PM:    - webpack
5:29:57 PM: ​
5:29:57 PM: These processes have been terminated. In case this creates a problem for your build, refer to this article for details about why this process termination happens and how to fix it.
```

Is the difference in `dev` and `prod`  because `laravel-mix` isn't allowed to complete? [Netlify's docs](https://answers.netlify.com/t/support-guide-build-completed-successfully-but-the-following-processes-were-still-running-how-to-remove/35277) suggest:

>To fix this, you should make sure the build command waits for its background processes before completing. In JavaScript, this often means properly following and calling promises, async/await, and callbacks.

I'm unsure what to do here. Thank you!

**Comment by chufucious** [comment]
Update: It seems if I `npm run production` and `git push` everything which includes `main.css`, `main.min.css`, `main.js` and `mix-manifest.json` then build on Netlify then the site looks correct. Am I messing up a configuration somewhere?

**Comment by josephdyer** [comment]
Hey, I'm not sure what that error is, but Netlify will run the `production` command for you automatically when you `git push` and build the production version of the site (minify and purge assets etc) - you don't need to run it before you git push.

`dev` just starts the local host server and compiles/watches the assets (scss, js & templates).

The `netlify.toml` file has the config in there for you already so you should be good to go for hosting on Netlify.
