### ISSUE TITLE
Issues with M1 and Laravel-Mix

### ISSUE THREAD

**Issue by MikeBinstock** [josephdyer/skeleventy#32]
I'am getting errors in M1 Mac without Rosetta2, and apparently is related to Laravel Mix.

Is anyone is having the same issue?

<img width="1183" alt="Captura de pantalla 2021-04-18 a las 9 37 39" src="https://user-images.githubusercontent.com/764/115686967-04551100-a35a-11eb-8cf9-c8c096b6f610.png">

**Comment by josephdyer** [comment]
https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/ 

Sorry, I don't have an M1 mac! You could try this?

**Comment by MikeBinstock** [comment]
Yes, it works with Rosetta2 without any problem. 
But the issue is related to a dependency not native (terminal-notifier)

**Comment by MikeBinstock** [comment]
More information about the issue:
https://github.com/JeffreyWay/laravel-mix/issues/2937#issuecomment-821985830

**Comment by MikeBinstock** [comment]
It is fixed.
