### ISSUE TITLE
CSS change not reflected in production

### ISSUE THREAD

**Issue by Stig11686** [josephdyer/skeleventy#35]
Great template!

I'm trying to make a small css change which is working in dev environment but not in production when deployed to netlify. Where do I start with this?! 

Thanks!

**Comment by emcog** [comment]
Have the same issue. Dev looks great but production doesn't carry across styles – font's etc. Really like Skeleventy and am reluctant to pick up a new template.

**Comment by emcog** [comment]
This could be an issue with google font when served from Netlify. I removed them from base.njk and it builds as intended. Without the fonts of course.

**Comment by Stig11686** [comment]
I think my issue relates to SCSS not compiling on build

**Comment by kct2020** [comment]
I had a similar problem deploying to Cloudflare Pages after changing SCSS.
I'm sorry that I can't recall the exact steps I took, but I think it involved a temporary change to deployment settings to: `npm run dev`.
So I'm guessing that changing the command line in netlify.toml should work. 
Hope that works, and sorry I can't be more definitive for now.

**Comment by Stig11686** [comment]
My issue solved: It was because I was trying to edit dynamically created elements and purge css - so the css was getting purged before the elements were being created. Solved by whitelisting the classes required.
