### ISSUE TITLE
Feature: Tag pages

### ISSUE THREAD

**Issue by spekulatius** [josephdyer/skeleventy#5]
Hello @josephdyer 

thanks for skeleventy, really nice blog template. I was wondering what you think about a tag page for all posts of particular tag?

Peter

**Comment by josephdyer** [comment]
Glad you like it dude :)

Sounds good - when I get chance I'll add to it!

Joe

**Comment by spekulatius** [comment]
Awesome, let me know if you want help and I can see what I can do :)

**Comment by kahboom** [comment]
Are there any plans to include this? I see there are categories but it would be nice to have both. Happy to contribute once I get more familiar with nunjucks.
