### ISSUE TITLE
Question: Pull Request for TW 1.0 Beta

### ISSUE THREAD

**Issue by afflexux** [josephdyer/skeleventy#6]
Alright @josephdyer 

First off, thanks for Skeleventy, its a pleasure to use.

Now, I'm not sure how I go about this so thought I'd ask first.

I've updated the boilerplate to use Tailwind 1.0b and made all the upgrade changes so it works.

I have forked your repo so could add the changes to there and open a pull request but I can see that goes to your master, as TW is still in beta I wasn't sure if thats the right way to go.

From what I can tell, there will be a final release any day now and shouldn't be any breaking changes.

As you can tell I'm new to pull requests!

How's best to proceed? Thanks.

**Comment by josephdyer** [comment]
Hey man - thanks, I'm glad it's of some use to you! You never know how much to include with starter boilerplates, in case people don't want it ;)

Yeah I'm aware that Tailwind v1 is out - I was just going to wait and update it, once Adam Wathan has done a full release, so don't worry too much about a pull request :)

Been a bit stretched for time recently, so haven't done much dev stuff outside of work - it's all on my to do list :D

Be cool to see the final site you've built once it's done!

**Comment by afflexux** [comment]
Alright Joe

I'd never use 11ty before and got up and running fairly quickly so its spot on what you included.

Yeah to be honest Adam has done a good job of keeping the upgrade fairly simple, if your pushed for time when the full release is out give me a shout and I'll add you to the private repo I've got it in and maybe it can save you a bit of grunt work!

Thanks again for Skeleventy, I'll get building something!
