### ISSUE TITLE
Big Blog

### ISSUE THREAD

**Issue by GerhardMes** [josephdyer/skeleventy#7]
Hi there, just playing around. But I have over 100 blog entries, and I can't find the css that automatically "page brake" the blog entries on the overview.

Lets say; max 4 blog entries in a row - or something else.

Is there an easy way to fix this?
Cheers Gerhard

PS: By the way; do you know an easy way to make a second language work within your starter or globally in eleventy? This would be a very interesting feature for me.

**Comment by josephdyer** [comment]
Hey! The CSS is controlled via the Tailwind classes in the HTML. But you can add CSS into the SCSS if you want to.

You would need to make the container around the articles `flex-wrap: wrap`, so they break onto a new line and then make each article to have a set width/flex-basis of 25% - in Tailwind you can use the class `w-1/4`. You might need to adjust the margins and padding too.

Not sure about multi-language stuff - you could ask Zach Leatherman who made Eleventy? ;)

**Comment by GerhardMes** [comment]
hi Joseph,
first: Thanks a lot. But I run into problems, which I would like to share.

I modified the blog.njk file at two fields as mentioned. 

<section id="container-centre" class="flex-1 flex-wrap:wrap container ml-auto mr-auto">
<div class="posts md:flex mb-4"> <! -- as mentioned at the tailwind help site -->
<article class="post flex flex-wrap:wrap w-1/4 flex-1 bg-white rounded-lg overflow-hidden">

But that doesn't change it. I couldn't make the line break after 4 Posts, and the images disappeared.

Do you have any advice?

**Comment by josephdyer** [comment]
It sounds like you have `flex-1` still on the articles? Try removing that.

See https://tailwindcss.com/docs/examples/grids/#wrapping-columns
