### ISSUE TITLE
Gulp compile failure for .js doesn't print location

### ISSUE THREAD

**Issue by montemartin** [josephdyer/skeleventy#8]
So far I'm blown away by how helpful this template is. I've run into a couple compile errors while  getting my base SCSS and tailwind.config set up. For SCSS errors it cleanly prints the filename:line:col and then gives a nice printout of the exact error. However for .js the error message is only the issue (e.g. `Error: Unexpected identifier`). It would be so much more helpful if the file and line number were included as well.

**Comment by josephdyer** [comment]
Hey man, glad to hear it's helpful!

Interesting - it's using plumber to log errors in the console, but not sure why the js side of things aren't working...when I get chance I'll have a look into it :)
